# Generated by Django 4.2 on 2023-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_car_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carinventory",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Car Inventory",
            },
        ),
        migrations.AlterField(
            model_name="carinventory",
            name="cars_value",
            field=models.FloatField(null=True),
        ),
    ]
