# Generated by Django 4.2 on 2023-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0006_alter_carinventory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="value",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
