# Generated by Django 4.2 on 2023-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0007_alter_car_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="carinventory",
            name="cars_value",
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
