# Generated by Django 4.2 on 2023-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0008_alter_car_value_alter_carinventory_cars_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
