# Generated by Django 4.2 on 2023-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0009_alter_car_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="factory_year",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_year",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=30, null=True
            ),
        ),
    ]
